services:
  db:
    image: postgres:16
    container_name: postgres_db
    environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    volumes:
        - pgdata:/var/lib/postgresql/data/

volumes:
  pgdata: